from tkinter import *
root=Tk()
root.title('Login')
root.iconbitmap("D:\\prgarmming class\\desktopapp\\abc.ico")
root.geometry("700x800")
name=Label(root,text='Username:',fg='Dark Blue',font=('Candara Light',13,'bold'))
name.place(x=30,y=50)
gender=Label(root,text="Gender:",fg='Dark Blue',font=('Candara Light',13,'bold'))
gender.place(x=30,y=80)
age=Label(root,text='Age:',fg='Dark Blue',font=('Candara Light',13,'bold'))
age.place(x=30,y=110)
adr=Label(root,text='Address:',fg='Dark Blue',font=('Candara Light',13,'bold'))
adr.place(x=30,y=140)
e1=Entry(root)
e1.place(x=130,y=50)
e2=Entry(root)
e2.place(x=130,y=80)
e3=Entry(root)
e3.place(x=130,y=110)
e4=Entry(root)
e4.place(x=130,y=140)
def add ():
    a=e1.get()
    lbl.config(text=a)
    e1.delete(0,END)
btn=Button(text="ClickMe",command=add)
btn.pack()
lbl=Label(text=" ")
lbl.pack()
root.mainloop()